dist: xenial

language: python

python:
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - python -m unittest discover tests/
    - python -m radon cc main.py form
    - python -m pylint main.py form
    - coverage run --source form/ -m unittest discover tests/

after_success:
    - codecov
